name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build, Push and Release a Docker container to Heroku.
              uses: akhileshns/heroku-deploy@v3.12.12
              env:
                  DB_CONN: ${{ secrets.DB_CONN }}
                  GCLOUD_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
                  GCS_BUCKET: ${{ secrets.GCS_BUCKET }}
                  GCS_KEYFILE: ${{ secrets.GCS_KEYFILE }}
                  LOGIN: ${{ secrets.LOGIN }}
                  PASSWORD: ${{ secrets.PASSWORD }}
                  JWT_SECRET: ${{ secrets.JWT_SECRET }}
              with:
                  heroku_email: ${{ secrets.HEROKU_EMAIL }}
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
                  usedocker: true
                  docker_build_args: |
                      DB_CONN
                      GCLOUD_PROJECT
                      GCS_BUCKET
                      GCS_KEYFILE
                      LOGIN
                      PASSWORD
                      JWT_SECRET

            - name: Setup node
              uses: actions/setup-node@master
              with:
                  node-version: '16.x'

            - name: Install Angualr node packages
              working-directory: ./client
              run: npm install

            - name: Build Angular app
              working-directory: ./client
              run: npm run build:prod

            - name: Deploy Angular app
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
                  PROJECT_PATH: 'client'
