name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Build, Push and Release a Docker container to Heroku.
              uses: gonuit/heroku-docker-deploy@v1.3.3
              with:
                  email: ${{ secrets.HEROKU_EMAIL }}
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
                  dockerfile_directory: ./
                  dockerfile_name: Dockerfile
                  docker_options: '--no-cache'
                  process_type: web

            - name: Build and Deploy Angular app
              uses: actions/setup-node@master
              with:
                  node-version: '16.x'
            - run: cd client && npm install
            - run: cd client && npm run build --aot
            - uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
